openapi: 3.0.0
paths:
  /support/estimations:
    post:
      operationId: estimateSupport
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SupportEstimationRequestDto'
      responses:
        '201':
          description: Endpoint to estimate the support eligibility and amount
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupportEstimationDto'
      tags:
        - geothermik
info:
  title: Geothermik Kata API
  description: The Geothermik API description
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  schemas:
    Civility:
      type: string
      enum:
        - M
        - Mme
    HouseholdIncomeAmount:
      type: object
      properties:
        value:
          type: number
          minimum: 10000
          maximum: 100000
      required:
        - value
    SupportEstimationRequestDto:
      type: object
      properties:
        civility:
          $ref: '#/components/schemas/Civility'
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        phoneNumber:
          type: string
        isOwner:
          type: boolean
        householdPersonCount:
          type: number
          minimum: 1
        householdIncomes:
          $ref: '#/components/schemas/HouseholdIncomeAmount'
        surface:
          type: number
          minimum: 1
      required:
        - civility
        - firstName
        - lastName
        - email
        - phoneNumber
        - isOwner
        - householdPersonCount
        - householdIncomes
        - surface
    Amount:
      type: object
      properties:
        value:
          type: number
          minimum: 0
      required:
        - value
    SupportEstimationDto:
      type: object
      properties:
        isEligible:
          type: boolean
          default: false
        supportAmount:
          $ref: '#/components/schemas/Amount'
        eligibilityMessage:
          type: string
      required:
        - isEligible
        - supportAmount
        - eligibilityMessage
